os: linux
language: node_js
node_js: 12
cache:
  npm: false
install:
  - echo "No install"  
stages:
  - name: setup
    if: type = pull_request OR type = push AND branch != master
  - name: lint
    if: false 
  - name: unit
    if: false
  - name: e2e
    if: false     
  - name: build
    if: false
  - name: deployment
    if: type = push  
jobs:
  fast_finish: true
  include:
    - stage: setup    
      script:
        - yarn checkcommit
    - stage: lint  
      node_js: 12
      dist: trusty
      cache:
        npm: false 
      before_install:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
      install:
        - yarn install --network-timeout 1000000 --frozen-lockfile  
      script:
        - yarn nx affected:lint --base=$(git merge-base HEAD $TRAVIS_BRANCH) HEAD --parallel
    - stage: unit  
      node_js: 12
      dist: trusty
      cache:
        npm: false  
      before_install:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
      install:
        - yarn install --network-timeout 1000000 --frozen-lockfile  
      script:
        - yarn nx affected:test --base=$(git merge-base HEAD $TRAVIS_BRANCH) HEAD --parallel 
    - stage: e2e  
      node_js: 12
      dist: trusty
      cache:
        npm: false
      addons:
        chrome: stable
        firefox: latest  
      before_install:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
      install:
        - yarn install --network-timeout 1000000 --frozen-lockfile  
      script:
        - yarn nx affected:e2e --base=$(git merge-base HEAD $TRAVIS_BRANCH) HEAD
    - stage: build  
      node_js: 12
      dist: trusty
      cache:
        npm: false 
      before_install:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
      install:
        - yarn install --network-timeout 1000000 --frozen-lockfile  
      script:
        - yarn nx affected:build --base=$(git merge-base HEAD $TRAVIS_BRANCH) HEAD --parallel      
    - stage: deployment
      node_js: 12
      dist: trusty
      cache:
        npm: false
      branches:
        only:
          - master  
      before_install:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
      script:
        - echo "start deployment"
       before_deploy: 
        - yarn vitaba-release"
       deploy:
        provider: npm
        email: info@sebasg.dev
        api_key: 4dd73c95-23c6-40ad-adf4-850c815867d0 
notifications:
  email: false
  webhooks:
    on_success: false
    on_failure: false
    on_start: false