os: linux
language: node_js
node_js: 12
dist: trusty
cache:
  npm: false
before_install:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
install:
  - yarn install --network-timeout 1000000 --frozen-lockfile
stages:
  - name: validation
    if: type = pull_request OR type = push
  - name: linting
    if: type = pull_request
  - name: testing
    if: type = pull_request
  - name: building
    if: type = pull_request OR (type = push AND head_branch = master)
  - name: deployment
    if: head_branch = master  
jobs:
  include:
    - stage: validation    
      script:
        - yarn checkcommit
    - stage: linting
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn nx affected:lint --base=$(git merge-base HEAD $TRAVIS_BRANCH) --parallel; fi'
    - stage: testing    
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn nx affected:test --base=$(git merge-base HEAD $TRAVIS_BRANCH) --parallel; fi' 
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn nx affected:e2e --base=$(git merge-base HEAD $TRAVIS_BRANCH) --parallel; fi'
    - stage: building  
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn nx affected:build --base=$(git merge-base HEAD $TRAVIS_BRANCH) --parallel; fi'    
    - stage: deployment
      after_script: 
        - yarn add firebase-tools
      script:
        - firebase deploy --only hosting:beta --non-interactive --token $FIREBASE_TOKEN;
        - yarn vitaba-release
        - yarn nx affected --target="deploy" --all --parallel;
 
notifications:
  email: true
  webhooks:
    on_success: true
    on_failure: true
    on_start: true