matrix:
  include:
    - os: linux
      language: node_js
      node_js: 12
      dist: trusty
      sudo: required
      cache:
        npm: false
      addons:
        chrome: stable
      before_install:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
      install:
        - yarn install --network-timeout 1000000 --frozen-lockfile
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn format:check --head=$TRAVIS_PULL_REQUEST_SHA --base=$(git merge-base HEAD $TRAVIS_BRANCH); fi'
        - yarn checkcommit
        - yarn nx affected:lint --base=$(git merge-base HEAD $TRAVIS_BRANCH)
    - os: linux
      language: node_js
      node_js: 12
      dist: trusty
      sudo: required
      cache:
        npm: false
      addons:
        chrome: stable
      before_install:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
      install:
        - yarn install --network-timeout 1000000 --frozen-lockfile
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn format:check --head=$TRAVIS_PULL_REQUEST_SHA --base=$(git merge-base HEAD $TRAVIS_BRANCH); fi'
        - yarn checkcommit
        - yarn nx affected:test --base=$(git merge-base HEAD $TRAVIS_BRANCH)
        - yarn nx affected:e2e --base=$(git merge-base HEAD $TRAVIS_BRANCH)
notifications:
  email: false
  webhooks:
    on_success: true
    on_failure: true
    on_start: true