matrix:
  include:
    - name: "lint"
    - os: linux
      language: node_js
      node_js: 12
      dist: trusty
      sudo: required
      cache:
        npm: false
      before_install:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
      install:
        - yarn install --network-timeout 1000000 --frozen-lockfile
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn nx affected:lint --base=$(git merge-base HEAD $TRAVIS_BRANCH) --parallel; fi'
        - yarn checkcommit
    - name: "test"
    - os: linux
      language: node_js
      node_js: 12
      dist: trusty
      sudo: required
      addons:
        chrome: stable
        firefox: latest
      cache:
        npm: false
      before_install:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
      install:
        - yarn install 
        - yarn install --network-timeout 1000000 --frozen-lockfile
      script:
        - yarn nx affected:test --base=$(git merge-base HEAD $TRAVIS_BRANCH) --parallel
        - yarn nx affected:e2e --base=$(git merge-base HEAD $TRAVIS_BRANCH) --parallel
    - name: "build"
    - os: linux
      language: node_js
      node_js: 12
      dist: trusty
      sudo: required
      addons:
        chrome: stable
        firefox: latest
      cache:
        npm: false
      before_install:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
      install:
        - yarn install 
        - yarn install --network-timeout 1000000 --frozen-lockfile
      script:
        - yarn nx affected:build --all --parallel 
    - name: "publish packages and apps"         
    - os: linux
    - branches:
      only:
        - master
      language: node_js
      node_js: 12
      dist: trusty
      sudo: required
      cache:
        npm: false
      before_install:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start;
      install:
        - yarn install --network-timeout 1000000 --frozen-lockfile
      script:
       - yarn nx affected:build --all --parallel
       after_success:
      - firebase deploy --only hosting:beta --non-interactive
      - yarn vitaba-release
notifications:
  email: false
  webhooks:
    on_success: true
    on_failure: true
    on_start: true